# Finding Exchange Rates for International Sales

![Header image](resources/image.jpg)

Exciting times! 

You've been running our very successful gadget webshop 'DataGadgets' for a few years and have recently expanded into new territories. While you've been focussed on the US market for the first five years of our existence, you now are shipping our cool data gadgets to the UK and Europe, too! But now our in-house built reporting has broken! Transactions don't only come in USD, but you're also receiving transactions in EUR and GPB. 

To better understand the volume of transactions being made, you should convert the non-USD transactions to USD and sum up the total. To do this, however, you'll need to use the proper exchange rates. 

In this project, you'll start with a CSV file containing all e-commerce transactions made on January 21st, but in their original currencies. Your job is to calculate the total sum in USD of all transactions so you know how much USD you sold on January 21st. To do this, you'll need to convert any non-USD transactions to USD using the exchange rate from January 21st, 2024. 

To get the exchange rates from January 21st, 2024, you'll rely on [VAT Comply rates API's](https://www.vatcomply.com/documentation#rates) public and free currency exchange API. You'll also use `pandas` to load the CSV file into a DataFrame and the `requests` package to make interacting with the API easier. 

You need to update the `orders` DataFrame so the final version has two new columns: `exchange_rate` and `amount_usd`. The final version should look as follows:

| `amount` | `currency` | `exchange_rate` | `amount_usd` |
|-|-|-|-|
| 43.75 | EUR | ... | ... |
| 385.5 | GBP | ... | ... |
| 495.5 | GBP | ... | ... |
| 117.99 | GBP | ... | ... |
| 624 | USD | ... | ... |

In [24]:
# Import required packages/libraries
import pandas as pd
import requests

# Read the CSV file into a DataFrame
orders = pd.read_csv(
    "Python/Python_programming/Finding Exchange Rates for International Sales/data/orders-2024-01-21.csv"
)
orders.head()

   amount currency
0   43.75      EUR
1  385.50      GBP
2  495.50      GBP
3  117.99      GBP
4  624.00      USD

In [25]:
# Request exchange rate 
params = {'date': '2024-01-21', 'base': 'USD'}
responses = requests.get('https://api.vatcomply.com/rates', params=params)

# Print the JSON text
print(responses.text)

{"date":"2024-01-19","base":"USD","rates":{"EUR":0.918527,"USD":1.0,"JPY":148.038946,"BGN":1.796454,"CZK":22.791403,"DKK":6.849913,"GBP":0.788326,"HUF":350.445485,"PLN":4.00643,"RON":4.572058,"SEK":10.452834,"CHF":0.868834,"ISK":136.768623,"NOK":10.480389,"TRY":30.192523,"AUD":1.515569,"BRL":4.908974,"CAD":1.346193,"CNY":7.191237,"HKD":7.819234,"IDR":15607.449251,"ILS":3.740333,"INR":83.079361,"KRW":1333.691559,"MXN":17.129972,"MYR":4.717461,"NZD":1.634794,"PHP":55.989713,"SGD":1.340957,"THB":35.459723,"ZAR":19.003582}}

In [26]:
# Decode into a Python object
rates = responses.json()
print(rates)

{'date': '2024-01-19', 'base': 'USD', 'rates': {'EUR': 0.918527, 'USD': 1.0, 'JPY': 148.038946, 'BGN': 1.796454, 'CZK': 22.791403, 'DKK': 6.849913, 'GBP': 0.788326, 'HUF': 350.445485, 'PLN': 4.00643, 'RON': 4.572058, 'SEK': 10.452834, 'CHF': 0.868834, 'ISK': 136.768623, 'NOK': 10.480389, 'TRY': 30.192523, 'AUD': 1.515569, 'BRL': 4.908974, 'CAD': 1.346193, 'CNY': 7.191237, 'HKD': 7.819234, 'IDR': 15607.449251, 'ILS': 3.740333, 'INR': 83.079361, 'KRW': 1333.691559, 'MXN': 17.129972, 'MYR': 4.717461, 'NZD': 1.634794, 'PHP': 55.989713, 'SGD': 1.340957, 'THB': 35.459723, 'ZAR': 19.003582}}

In [27]:
# Map the corresponding currency rate
def set_value(currency, mapping):
    return mapping[currency]

# Add exchange rate column 
mapping_dict = rates['rates']
orders['exchange_rate'] = orders['currency'].apply(set_value, args=(mapping_dict,))

In [28]:
# Add sales in USD column
orders['amount_usd'] = orders['amount'] * orders['exchange_rate']

In [29]:
# Check the updated the DataFrame 
orders.head()

   amount currency  exchange_rate  amount_usd
0   43.75      EUR       0.918527   40.185556
1  385.50      GBP       0.788326  303.899673
2  495.50      GBP       0.788326  390.615533
3  117.99      GBP       0.788326   93.014585
4  624.00      USD       1.000000  624.000000

In [31]:
# Sum up all the sales
total_usd_sales = orders['amount_usd'].sum()
print(round(total_usd_sales, 2))

326864.49